---
- project:
    check:
      jobs:
        - tox-py37-cover
        - coverage-diff:
            voting: false
            dependencies:
              - tox-py37-cover-previous
              - tox-py37-cover
            vars:
              coverage_job_name_previous: tox-py37-cover-previous
              coverage_job_name_current: tox-py37-cover
        - tox-docs
        - tox-linters:
            voting: false
        - tox-py37-cover-previous
    gate:
      jobs:
        - tox-py37
        - tox-docs
