---
- project:
    check:
      jobs:
        - tox-py37-cover:
            vars:
              python_use_pyenv: false
        - coverage-diff:
            voting: false
            dependencies:
              - tox-py37-cover-previous
              - tox-py37-cover
            vars:
              coverage_job_name_previous: tox-py37-cover-previous
              coverage_job_name_current: tox-py37-cover
        - tox-linters-diff:
            voting: false
        - tox-docs
        - tox-py36
        - tox-py37-cover-previous:
            vars:
              python_use_pyenv: false
    gate:
      jobs:
        - tox-py36
        - tox-py37
        - tox-docs
