---
# TODO: remove once https://review.opendev.org/c/712804/ gets merged upstream
- job:
    name: tox-py37-oopt-gnpy
    parent: tox-py37
    vars:
      tox_prefer_python2: false

- project:
    check:
      jobs:
      - tox-py37-oopt-gnpy
    gate:
      jobs:
      - tox-py37-oopt-gnpy
